<?xml version="1.0" encoding="utf-8" ?>
<project name="matrix-kotlin-crypto" default="jar" basedir="." xmlns:ivy="antlib:org.apache.ivy.ant">
    <property name="source" location="src"/>
    <property name="bin" location="bin/"/>
    <property name="dist-dir"  location="dist"/>
    <property name="lib-source"  location="lib"/>
    <property name="lib-local-source"  location="lib-local"/>
    <property name="resources"  location="resources"/>

    <property name="project-name" value="${ant.project.name}" />

    <property environment="env"/>
    <taskdef file="${env.KOTLIN_HOME}/build-tools/ant/src/org/jetbrains/jet/buildtools/ant/antlib.xml">
        <classpath>
            <fileset dir="${env.KOTLIN_HOME}/dist/kotlinc/lib" includes="*.jar"/>
        </classpath>
    </taskdef>


    <target name="init">
        <mkdir dir="${dist-dir}"/>
        <mkdir dir="${lib-source}"/>
        <mkdir dir="${bin}"/>
    </target>

    <target name="resolve" depends="init">
        <ivy:retrieve type="jar,bundle" />
    </target>

    <target name="compile" depends="resolve">

        <javac srcdir="${source}" destdir="${bin}">
            <classpath>
                <!-- Ivy retrieves dependencies here -->
                <fileset dir="${lib-source}" includes="**/*.jar"/>
            </classpath>
        </javac>
    </target>

    <target name="jar" depends="compile" description="Create a jar file">
        <jar jarfile="${dist-dir}/${ant.project.name}.jar" basedir="${bin}">
            <fileset dir="${source}" includes="**/*.java" />
        </jar>
    </target>

    <target name="clean" description="Cleans this project">
        <delete dir="${bin}" failonerror="false" />
        <delete dir="${dist-dir}" failonerror="false" />
        <delete dir="${lib-source}" failonerror="false" />
    </target>
</project>
