<?xml version="1.0" encoding="UTF-8" ?>
<ivy-module version="2.0">

    <info organisation="com.audriga" module="cloudmovr.${project-name}" revision="0.1" />
    <publications>
        <artifact name="cloudmovr.${project-name}" type="jar" ext="jar"/>
    </publications>
    <dependencies>
        <dependency org="net.java.dev.jna" name="jna" rev="5.18.1"/>
        <dependency org="org.jetbrains.kotlin" name="kotlin-stdlib" rev="2.3.0"/>
        <dependency org="org.json" name="json" rev="20251224"/>
        <dependency org="com.squareup.moshi" name="moshi" rev="1.15.1"/>
        <dependency org="com.squareup.moshi" name="moshi-adapters" rev="1.15.1"/>
        <dependency org="com.squareup.moshi" name="moshi-kotlin-codegen" rev="1.15.1"/>
        <dependency org="com.squareup.okhttp3" name="okhttp" rev="4.11.0"/>
    </dependencies>
</ivy-module>