// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "UNUSED_PARAMETER", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN", "IMPLICIT_NOTHING_TYPE_ARGUMENT_IN_RETURN_POSITION")

package keybackup

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import kotlin.Any
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.Map
import kotlin.collections.emptySet
import kotlin.text.buildString

internal class CreateKeysBackupVersionBodyJsonAdapter(
  moshi: Moshi,
) : JsonAdapter<CreateKeysBackupVersionBody>() {
  private val options: JsonReader.Options = JsonReader.Options.of("algorithm", "auth_data")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java, emptySet(),
      "algorithm")

  private val mapOfStringAnyAdapter: JsonAdapter<Map<String, Any>> =
      moshi.adapter(Types.newParameterizedType(Map::class.java, String::class.java,
      Any::class.java), emptySet(), "authData")

  public override fun toString(): String = buildString(49) {
      append("GeneratedJsonAdapter(").append("CreateKeysBackupVersionBody").append(')') }

  public override fun fromJson(reader: JsonReader): CreateKeysBackupVersionBody {
    var algorithm: String? = null
    var authData: Map<String, Any>? = null
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> algorithm = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("algorithm",
            "algorithm", reader)
        1 -> authData = mapOfStringAnyAdapter.fromJson(reader) ?:
            throw Util.unexpectedNull("authData", "auth_data", reader)
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    return CreateKeysBackupVersionBody(
        algorithm = algorithm ?: throw Util.missingProperty("algorithm", "algorithm", reader),
        authData = authData ?: throw Util.missingProperty("authData", "auth_data", reader)
    )
  }

  public override fun toJson(writer: JsonWriter, value_: CreateKeysBackupVersionBody?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("algorithm")
    stringAdapter.toJson(writer, value_.algorithm)
    writer.name("auth_data")
    mapOfStringAnyAdapter.toJson(writer, value_.authData)
    writer.endObject()
  }
}
