// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "UNUSED_PARAMETER", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN", "IMPLICIT_NOTHING_TYPE_ARGUMENT_IN_RETURN_POSITION")

package keybackup

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

internal class RestKeyInfoJsonAdapter(
  moshi: Moshi,
) : JsonAdapter<RestKeyInfo>() {
  private val options: JsonReader.Options = JsonReader.Options.of("user_id", "usage", "keys",
      "signatures")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java, emptySet(),
      "userId")

  private val nullableListOfStringAdapter: JsonAdapter<List<String>?> =
      moshi.adapter(Types.newParameterizedType(List::class.java, String::class.java), emptySet(),
      "usages")

  private val nullableMapOfStringStringAdapter: JsonAdapter<Map<String, String>?> =
      moshi.adapter(Types.newParameterizedType(Map::class.java, String::class.java,
      String::class.java), emptySet(), "keys")

  private val nullableMapOfStringMapOfStringStringAdapter:
      JsonAdapter<Map<String, Map<String, String>>?> =
      moshi.adapter(Types.newParameterizedType(Map::class.java, String::class.java,
      Types.newParameterizedType(Map::class.java, String::class.java, String::class.java)),
      emptySet(), "signatures")

  @Volatile
  private var constructorRef: Constructor<RestKeyInfo>? = null

  public override fun toString(): String = buildString(33) {
      append("GeneratedJsonAdapter(").append("RestKeyInfo").append(')') }

  public override fun fromJson(reader: JsonReader): RestKeyInfo {
    var userId: String? = null
    var usages: List<String>? = null
    var keys: Map<String, String>? = null
    var signatures: Map<String, Map<String, String>>? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> userId = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("userId",
            "user_id", reader)
        1 -> usages = nullableListOfStringAdapter.fromJson(reader)
        2 -> keys = nullableMapOfStringStringAdapter.fromJson(reader)
        3 -> {
          signatures = nullableMapOfStringMapOfStringStringAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 3).inv()
          mask0 = mask0 and 0xfffffff7.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffff7.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  RestKeyInfo(
          userId = userId ?: throw Util.missingProperty("userId", "user_id", reader),
          usages = usages,
          keys = keys,
          signatures = signatures
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<RestKeyInfo> = this.constructorRef ?:
          RestKeyInfo::class.java.getDeclaredConstructor(String::class.java, List::class.java,
          Map::class.java, Map::class.java, Int::class.javaPrimitiveType,
          Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
      return localConstructor.newInstance(
          userId ?: throw Util.missingProperty("userId", "user_id", reader),
          usages,
          keys,
          signatures,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: RestKeyInfo?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("user_id")
    stringAdapter.toJson(writer, value_.userId)
    writer.name("usage")
    nullableListOfStringAdapter.toJson(writer, value_.usages)
    writer.name("keys")
    nullableMapOfStringStringAdapter.toJson(writer, value_.keys)
    writer.name("signatures")
    nullableMapOfStringMapOfStringStringAdapter.toJson(writer, value_.signatures)
    writer.endObject()
  }
}
