// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "UNUSED_PARAMETER", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN", "IMPLICIT_NOTHING_TYPE_ARGUMENT_IN_RETURN_POSITION")

package keybackup

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Any
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.Map
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

internal class UploadSigningKeysBodyJsonAdapter(
  moshi: Moshi,
) : JsonAdapter<UploadSigningKeysBody>() {
  private val options: JsonReader.Options = JsonReader.Options.of("master_key", "self_signing_key",
      "user_signing_key", "auth")

  private val nullableRestKeyInfoAdapter: JsonAdapter<RestKeyInfo?> =
      moshi.adapter(RestKeyInfo::class.java, emptySet(), "masterKey")

  private val nullableMapOfStringNullableAnyAdapter: JsonAdapter<Map<String, *>?> =
      moshi.adapter(Types.newParameterizedType(Map::class.java, String::class.java,
      Types.subtypeOf(Any::class.java)), emptySet(), "auth")

  @Volatile
  private var constructorRef: Constructor<UploadSigningKeysBody>? = null

  public override fun toString(): String = buildString(43) {
      append("GeneratedJsonAdapter(").append("UploadSigningKeysBody").append(')') }

  public override fun fromJson(reader: JsonReader): UploadSigningKeysBody {
    var masterKey: RestKeyInfo? = null
    var selfSigningKey: RestKeyInfo? = null
    var userSigningKey: RestKeyInfo? = null
    var auth: Map<String, *>? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          masterKey = nullableRestKeyInfoAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          selfSigningKey = nullableRestKeyInfoAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        2 -> {
          userSigningKey = nullableRestKeyInfoAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 2).inv()
          mask0 = mask0 and 0xfffffffb.toInt()
        }
        3 -> {
          auth = nullableMapOfStringNullableAnyAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 3).inv()
          mask0 = mask0 and 0xfffffff7.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffff0.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  UploadSigningKeysBody(
          masterKey = masterKey,
          selfSigningKey = selfSigningKey,
          userSigningKey = userSigningKey,
          auth = auth
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<UploadSigningKeysBody> = this.constructorRef ?:
          UploadSigningKeysBody::class.java.getDeclaredConstructor(RestKeyInfo::class.java,
          RestKeyInfo::class.java, RestKeyInfo::class.java, Map::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          masterKey,
          selfSigningKey,
          userSigningKey,
          auth,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: UploadSigningKeysBody?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("master_key")
    nullableRestKeyInfoAdapter.toJson(writer, value_.masterKey)
    writer.name("self_signing_key")
    nullableRestKeyInfoAdapter.toJson(writer, value_.selfSigningKey)
    writer.name("user_signing_key")
    nullableRestKeyInfoAdapter.toJson(writer, value_.userSigningKey)
    writer.name("auth")
    nullableMapOfStringNullableAnyAdapter.toJson(writer, value_.auth)
    writer.endObject()
  }
}
